/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.cput.frontendcarservicemanagement.view;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import za.ac.cput.frontendcarservicemanagement.client.CustomerClient;
import za.ac.cput.frontendcarservicemanagement.entity.Customer;

/**
 *
 * @author kurtj
 */
public class CustomerPnl extends JFrame {
    CustomerClient customerClient = new CustomerClient();

    /**
     * Creates new form CustomerPnl
     */
    public CustomerPnl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerPnl = new javax.swing.JPanel();
        customerSidePnl = new javax.swing.JPanel();
        showCusBtn = new javax.swing.JButton();
        addCustomerBtn = new javax.swing.JButton();
        deleteCustomerBtn = new javax.swing.JButton();
        updateCustomer = new javax.swing.JButton();
        cusFormPnl = new javax.swing.JPanel();
        idLbl = new javax.swing.JLabel();
        idLbl1 = new javax.swing.JLabel();
        idLbl2 = new javax.swing.JLabel();
        idLbl3 = new javax.swing.JLabel();
        idLbl4 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerSidePnl.setBackground(new java.awt.Color(136, 149, 141));

        showCusBtn.setBackground(new java.awt.Color(102, 102, 102));
        showCusBtn.setText("All Customers");
        showCusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showCusBtnMouseClicked(evt);
            }
        });
        showCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCusBtnActionPerformed(evt);
            }
        });

        addCustomerBtn.setBackground(new java.awt.Color(102, 102, 102));
        addCustomerBtn.setText("Add");
        addCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerBtnMouseClicked(evt);
            }
        });
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });

        deleteCustomerBtn.setBackground(new java.awt.Color(102, 102, 102));
        deleteCustomerBtn.setText("Delete");
        deleteCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCustomerBtnMouseClicked(evt);
            }
        });
        deleteCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerBtnActionPerformed(evt);
            }
        });

        updateCustomer.setBackground(new java.awt.Color(102, 102, 102));
        updateCustomer.setText("Update");
        updateCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateCustomerMouseClicked(evt);
            }
        });
        updateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerSidePnlLayout = new javax.swing.GroupLayout(customerSidePnl);
        customerSidePnl.setLayout(customerSidePnlLayout);
        customerSidePnlLayout.setHorizontalGroup(
            customerSidePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerSidePnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(customerSidePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showCusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        customerSidePnlLayout.setVerticalGroup(
            customerSidePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerSidePnlLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(addCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(deleteCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(updateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(showCusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        idLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idLbl.setText("ID:");

        idLbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idLbl1.setText("Name:");

        idLbl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idLbl2.setText("Email:");

        idLbl3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idLbl3.setText("Lastname:");

        idLbl4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idLbl4.setText("Address:");

        idTxt.setEditable(false);
        idTxt.setBackground(new java.awt.Color(51, 51, 51));

        nameTxt.setBackground(new java.awt.Color(51, 51, 51));

        emailTxt.setBackground(new java.awt.Color(51, 51, 51));

        lastNameTxt.setBackground(new java.awt.Color(51, 51, 51));

        addressTxt.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout cusFormPnlLayout = new javax.swing.GroupLayout(cusFormPnl);
        cusFormPnl.setLayout(cusFormPnlLayout);
        cusFormPnlLayout.setHorizontalGroup(
            cusFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusFormPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cusFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(idLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idLbl4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cusFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(lastNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        cusFormPnlLayout.setVerticalGroup(
            cusFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusFormPnlLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(cusFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cusFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl1)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cusFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl3)
                    .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cusFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl2)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(cusFormPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl4)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout customerPnlLayout = new javax.swing.GroupLayout(customerPnl);
        customerPnl.setLayout(customerPnlLayout);
        customerPnlLayout.setHorizontalGroup(
            customerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPnlLayout.createSequentialGroup()
                .addComponent(customerSidePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusFormPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customerPnlLayout.setVerticalGroup(
            customerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerSidePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cusFormPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JPanel getCustomerPanel(){
       return this.customerPnl;
    }
    
    
    
    
    private void showCusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showCusBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showCusBtnMouseClicked

    private void showCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCusBtnActionPerformed
        if(evt.getActionCommand().equals("All Customers")){
             CustomerClient getAllCustomers = new CustomerClient();
             showAllCustomers = new ShowAll();
             showAllCustomers.setVisible(true);
        }
    }//GEN-LAST:event_showCusBtnActionPerformed

    private void addCustomerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerBtnMouseClicked

    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed
        if(evt.getSource()==addCustomerBtn){
            customerClient.saveCustomer(this.nameTxt.getText().toString(), 
                    this.lastNameTxt.getText().toString(), 
                    this.emailTxt.getText().toString(),
                    this.addressTxt.getText().toString());
        }
    }//GEN-LAST:event_addCustomerBtnActionPerformed

    private void deleteCustomerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCustomerBtnMouseClicked

    private void deleteCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCustomerBtnActionPerformed

    private void updateCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateCustomerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateCustomerMouseClicked

    private void updateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateCustomerActionPerformed

    public JTextField getAddressTxt() {
        return addressTxt;
    }

    public JTextField getEmailTxt() {
        return emailTxt;
    }

    public JTextField getIdTxt() {
        return idTxt;
    }

    public JTextField getLastNameTxt() {
        return lastNameTxt;
    }

    public JTextField getNameTxt() {
        return nameTxt;
    }

    public void setAddressTxt(JTextField addressTxt) {
        this.addressTxt = addressTxt;
    }

    public void setEmailTxt(JTextField emailTxt) {
        this.emailTxt = emailTxt;
    }

    public void setIdTxt(JTextField idTxt) {
        this.idTxt = idTxt;
    }

    public void setLastNameTxt(JTextField lastNameTxt) {
        this.lastNameTxt = lastNameTxt;
    }

    public void setNameTxt(JTextField nameTxt) {
        this.nameTxt = nameTxt;
    }
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPnl().setVisible(true);
            }
        });
    }
    
    private ShowAll showAllCustomers;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JPanel cusFormPnl;
    private javax.swing.JPanel customerPnl;
    private javax.swing.JPanel customerSidePnl;
    private javax.swing.JButton deleteCustomerBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel idLbl;
    private javax.swing.JLabel idLbl1;
    private javax.swing.JLabel idLbl2;
    private javax.swing.JLabel idLbl3;
    private javax.swing.JLabel idLbl4;
    private javax.swing.JTextField idTxt;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton showCusBtn;
    private javax.swing.JButton updateCustomer;
    // End of variables declaration//GEN-END:variables
}
